'use strict';

let guardChat = [
  '...',
  '*chew gum*',
  '*guarding*',
  '*sneeze*',
  '*snore*',
  '*zzzzzzz*',
  'achtung!',
  'bored now',
  'feet hurt',
  'food time?',
  'go away',
  'good times',
  'have 2 pee',
  'hmmmmm',
  'I h8 rain',
  'I\'m cold',
  'mmm beer',
  'papers plz',
  'so bored',
  'squirrel!',
  'who goes?'
];

let motivations = [
  '*cough*',
  'bleargh',
  'chop chop!',
  'do it!',
  'do it now!',
  'doing good',
  'don\'t quit',
  'don\'t stop',
  'faster!',
  'harder!',
  'just do it',
  'keep it up',
  'longer!',
  'meh',
  'more work!',
  'more!',
  'no fear!',
  'no rest!',
  'no slack!',
  'quick now!',
  'succeed!',
  'trust in u',
  'u can win!',
  'u r great!',
  'u r super!',
  'u will win',
  'win now!',
  'work fast!',
  'work hard!',
  'work now!',
  'yes u can!',
  'you can!'
];

let names = [
  "4Real",
  "Adeline",
  "Alucard",
  "AmberWaves",
  "Apple",
  "ArthurDent",
  "Audi",
  "Bandit",
  "Banjo",
  "BearWhistle",
  "Blaer",
  "BluebellMadonna",
  "BlueIvy",
  "BodhiRansom",
  "BooWeakly",
  "BriarRose",
  "Bridge",
  "BronxMowgli",
  "BuddyBear",
  "Burger",
  "BuzzMichelangelo",
  "Camera",
  "CherryGrant",
  "ChestRockwell",
  "ChowTow",
  "CricketPearl",
  "DaisyBoo",
  "DangardAce",
  "Darriah",
  "Destry",
  "Diezelky",
  "DirkDiggler",
  "Dough",
  "Egypt",
  "Ein",
  "Faye",
  "FifiTrixibelle",
  "FishAndChips",
  "FordPrefect",
  "FoxIndia",
  "Friday",
  "Grammophon",
  "HavenT",
  "HeavenlyHiraaniTigerLily",
  "Huckleberry",
  "IndiaRose",
  "InigoMontoya",
  "Jermajesty",
  "Jet",
  "JoelleRollo",
  "JustinCase",
  "KalEl",
  "Kaneda",
  "Katniss",
  "Kix",
  "Levaeh",
  "MafiaNoFear",
  "Manhattan",
  "MegaaOmariGrandberry",
  "Mildred",
  "MmmBread",
  "MoonUnit",
  "MostPopular",
  "MoxieCrimefighter",
  "MustardMMustard",
  "NorthWest",
  "Nutella",
  "Ocean",
  "Pawk",
  "Peanut",
  "PilotInspektor",
  "PrincessTiaamii",
  "Puma",
  "RadicalEdward",
  "RazorShines",
  "ReedRothchild",
  "RiverRose",
  "Rollergirl",
  "RoyalReign",
  "RoyMustang",
  "SaintLazslo",
  "Sansa",
  "SatchelFarrow",
  "SevenSirius",
  "Sirjames",
  "Smellie",
  "Snape",
  "South",
  "SparrowMidnight",
  "Speedy",
  "Spike",
  "Stompie",
  "SummerRain",
  "SundayRose",
  "TalulaDoesTheHulaFromHawaii",
  "Tetsuo",
  "Thinn",
  "TitanJewell",
  "ToastedTeacake",
  "Tokyo",
  "Trillian",
  "TuMorrow",
  "Twelve",
  "UriahHeep",
  "VerucaSalt",
  "Vodka",
  "WhiskeyDanger",
  "WillPower",
  "WyattIsabelle",
  "Xzayvian",
  "Yoga",
  "Zealand",
  "Ziggurat"
];

let titles = {
  banker: 'Hoarder',
  builder: 'Architect',
  carter: 'Stevedore',
  courier: 'Dispatcher',
  decoy: 'Decoy',
  energizer: 'Energizer',
  fixer: 'Mender',
  guard: 'Protector',
  harvester: 'Reaper',
  keeperHunter: 'Slayer',
  longHauler: 'Waggoner',
  miner: 'Prospector',
  pioneer: 'Conquistador',
  raider: 'Marauder',
  remoteHarvester: 'Cultivator',
  scout: 'Vanguard',
  staticHarvester: 'Stockpiler',
  supplier: 'Provisioner',
  thief: 'Burglar',
  upgrader: 'Enhancer'
};

module.exports = {
  guardChat: guardChat,
  names: names,
  motivations: motivations,
  titles: titles
};
